DROP TABLE IF EXISTS `Player`;
DROP TABLE IF EXISTS `Game`;
DROP TABLE IF EXISTS `Liga`;
DROP TABLE IF EXISTS `Team`;


CREATE TABLE `Liga` (
	`Name` NVARCHAR (50) NOT NULL,
	`Year` CHAR (4) NOT NULL,
`IsInPlanning` BOOLEAN NULL,
	`Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	CONSTRAINT PRIMARY KEY(Id)
);